version: "3"
services:
  backend-msproduct:
    build: ./backend/msproduct
    ports:
      - "8083:8081"
  backend-msorder:
    build: ./backend/msorder
    ports:
      - "8084:8082"
  frontend:
    build: ./front
    ports:
      - "8082:3000"
