spring:
  application:
    name: msorder
  doc:
    api-docs:
      path: /api-docs

server:
  port: 8082

store:
  frontend:
    url: "http://localhost:3000"

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,PATCH"
  allowed-headers: "*"
  allow-credentials: true
