apiVersion: apps/v1
kind: Deployment
metadata:
  name: msorder-deployment
  namespace: store-application

spec:
  replicas: 1

  selector:
    matchLabels:
      app: msorder

  template:
    metadata:
      labels:
        app: msorder
    spec:
      containers:
      - name: msorder
        image: aminedatabases/msorder:latest
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
