apiVersion: apps/v1
kind: Deployment
metadata:
  name: msproduct-deployment
  namespace: store-application

spec:
  replicas: 1

  selector:
    matchLabels:
      app: msproduct

  template:
    metadata:
      labels:
        app: msproduct
    spec:
      containers:
      - name: backend
        image: aminedatabases/msproduct:latest
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
